# Generated by Django 5.2.1 on 2025-08-06 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='プロモションコードは7桁の英数字', regex='^[A-Za-z0-9]{7}$')])),
                ('discount_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
