# Generated by Django 5.2.1 on 2025-06-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://dummyimage.com/600x400/000/fff'),
            preserve_default=False,
        ),
    ]
