# Generated by Django 5.2.1 on 2025-08-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0005_order_promo_code_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
