# Generated by Django 5.2.1 on 2025-08-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0006_orderproduct_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='dummy',
        ),
    ]
