# Generated by Django 5.2.1 on 2025-07-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='type')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('card_number', models.CharField(max_length=30, verbose_name='card_number')),
                ('expiration', models.CharField(max_length=30, verbose_name='expriration')),
                ('cvv', models.CharField(max_length=30, verbose_name='cvv')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('user_name', models.CharField(max_length=30, verbose_name='user_name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='address')),
                ('address2', models.CharField(blank=True, max_length=30, verbose_name='address2')),
                ('country', models.CharField(max_length=30, verbose_name='country')),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('zip', models.CharField(max_length=30, verbose_name='zip')),
            ],
        ),
    ]
