# Generated by Django 5.2.1 on 2025-07-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0007_card_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ec_site.order'),
        ),
        migrations.AddField(
            model_name='card',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ec_site.product'),
        ),
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
