# Generated by Django 5.2.1 on 2025-07-31 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0009_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
