# Generated by Django 5.2.1 on 2025-07-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0010_alter_order_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
    ]
