# Generated by Django 5.2.1 on 2025-07-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0014_alter_order_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
