# Generated by Django 5.2.1 on 2025-07-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec_site', '0015_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='create_at',
        ),
    ]
